Реализации конструкции try catch
Для добавления отслеживания ошибок можно прописать следующий код:
<pre><code class="language-cpp">try { // В блоке try мы пытаемся выполнить какой-либо код
    if (variable == 0) // Проверяем делитель на ноль
        throw 277; // Запускаем исключение и передаем в него параметр

    cout &amp;lt;&amp;lt; something / variable &amp;lt;&amp;lt; endl; 
} catch(int i) { // Здесь отлавливаем переданную ошибку
    cout &amp;lt;&amp;lt; &quot;Нам очень повезло!&quot; &amp;lt;&amp;lt; endl;
    cout &amp;lt;&amp;lt; &quot;Нам удалось избежать ошибки с индексом &quot; &amp;lt;&amp;lt; i &amp;lt;&amp;lt; &quot; - на 0 делить нельзя!&quot;;
}
</code></pre>
В коде выше представлен очень простой пример использования исключений. 
Не обращайте внимание на его простоту, так как главное это рассмотреть общую конструкцию блока try catch.
При использовании такой конструкции, какая бы ошибка не получилась в ходе программы 
сама программа работать не перестанет и пользователь не получить плохой опыт в её использовании.
Если необходимо отследить несколько классов с ошибками, то можно добавить несколько 
блоков catch. Все они добавляются друг под другом точно также как в условных операторах.